export const populerData = [
  {
    id: "1",
    title: "Image to PDF",
    icon: "file-image",
    color: "rgba(249, 115, 22, 1)",
    route: "UploadPDF",
  },
  {
    id: "2",
    title: "Marge PDF",
    icon: "fork",
    color: "rgba(59, 130, 246, 1)",
    route: "UploadPDF",
  },
  {
    id: "3",
    title: "Add Header & Footer",
    icon: "file-text",
    color: "rgba(16, 185, 129, 1)",
    route: "UploadPDF",
  },
  {
    id: "4",
    title: "Page Number",
    icon: "field-number",
    color: "rgba(139, 92, 246, 1)",
    route: "UploadPDF",
  },
  {
    id: "5",
    title: "Compress PDF",
    icon: "compress",
    color: "rgba(236, 72, 153, 1)",
    route: "UploadPDF",
  },
  {
    id: "6",
    title: "Excel to PDF",
    icon: "file-excel",
    color: "rgba(34, 197, 94, 1)",
    route: "UploadPDF",
  },
  {
    id: "7",
    title: "Pdf Watermark",
    icon: "highlight",
    color: "rgba(245, 158, 11, 1)",
    route: "UploadPDF",
  },
  {
    id: "8",
    title: "Word to PDF",
    icon: "file-word",
    color: "rgba(37, 99, 235, 1)",
    route: "UploadPDF",
  },
  {
    id: "9",
    title: "Merge PDF",
    icon: "branches",
    color: "rgba(14, 165, 233, 1)",
    route: "UploadPDF",
  },
  {
    id: "10",
    title: "PDF Scanner",
    icon: "scan",
    color: "rgba(14, 165, 233, 1)",
    route: "UploadPDF",
  },

];

export const allToolsData = [
    {
    id: "1",
    title: "Compress PDF",
    icon: "compress",
    color: "rgba(236, 72, 153, 1)",
    route: "UploadPDF",
  },
  {
    id: "2",
    title: "Merge PDF",
    icon: "branches",
    color: "rgba(14, 165, 233, 1)",
    route: "UploadPDF",
  },
    {
    id: "3",
    title: "Excel to PDF",
    icon: "file-excel",
    color: "rgba(34, 197, 94, 1)",
    route: "UploadPDF",
  },
  {
    id: "4",
    title: "Image to PDF",
    icon: "file-image",
    color: "rgba(249, 115, 22, 1)",
    route: "UploadPDF",
  },
   {
    id: "5",
    title: "Page Number",
    icon: "field-number",
    color: "rgba(139, 92, 246, 1)",
    route: "UploadPDF",
  },
  {
    id: "6",
    title: "Marge PDF",
    icon: "fork",
    color: "rgba(59, 130, 246, 1)",
    route: "UploadPDF",
  },
  {
    id: "7",
    title: "Add Header & Footer",
    icon: "file-text",    
    color: "rgba(16, 185, 129, 1)",    
    route: "UploadPDF",
  },
  {
    id: "8",
    title: "Pdf Watermark",
    icon: "highlight",
    color: "rgba(245, 158, 11, 1)",
    route: "UploadPDF",
  },
  {
    id: "9",
    title: "Word to PDF",
    icon: "file-word",
    color: "rgba(37, 99, 235, 1)",
    route: "UploadPDF",
  },
  
  {
    id: "10",
    title: "PDF Scanner",
    icon: "scan",
    color: "rgba(14, 165, 233, 1)",
    route: "UploadPDF",
  },
  {
    id: "11",
    title: "Crop PDF",
    icon: "copyright-circle",
    color: "rgba(16, 185, 129, 1)",
    route: "UploadPDF",
  },
  {
    id: "12",
    title: "Resize PDF",
    icon: "block",
    color: "rgba(245, 40, 145, 0.8)",
    route: "UploadPDF",
  },
  {
    id: "13",
    title: "File to ZIP",
    icon: "file-zip",
    color: "rrgba(37, 99, 235, 1)",
    route: "UploadPDF",
  },

]

