export const populerData = [
  {
    id: "1",
    title: "Image to PDF",
    icon: "file-image",
    color: "rgba(249, 115, 22, 1)",
    route: "UploadPDF",
  },
  {
    id: "2",
    title: "View PDF",
    icon: "file-pdf",
    color: "rgba(59, 130, 246, 1)",
    route: "FileManager",
  },
  {
    id: "3",
    title: "File",
    icon: "folder-open",
    color: "rgba(14, 179, 16, 1)",
    route: "FileManager",
  },
  {
    id: "4",
    title: "Marge PDF",
    icon: "fork",
    color: "rgba(59, 130, 246, 1)",
    route: "MargePDF",
  },
  {
    id: "5",
    title: "Add Header & Footer",
    icon: "file-text",
    color: "rgba(5, 132, 137, 0.8)",
    route: "AddHeaderFooter",
  },
  {
    id: "6",
    title: "Page Number",
    icon: "field-number",
    color: "rgba(139, 92, 246, 1)",
    route: "PageNumber",
  },
  {
    id: "7",
    title: "Compress PDF",
    icon: "compress",
    color: "rgba(236, 72, 153, 1)",
    route: "CompressPDF",
  },
  {
    id: "8",
    title: "QR Code Generator",
    icon: "qrcode",
    color: "rgba(34, 197, 94, 1)",
    route: "QrGenerator",
  },
  {
    id: "9",
    title: "Pdf Watermark",
    icon: "highlight",
    color: "rgba(245, 158, 11, 1)",
    route: "PdfWatermark",
  },
  {
    id: "10",
    title: "Resize PDF",
    icon: "block",
    color: "rgba(245, 40, 145, 0.8)",
    route: "ResizePDF",
  },

  {
    id: "11",
    title: "QR Code Scanner",
    icon: "scan",
    color: "rgba(14, 165, 233, 1)",
    route: "QrScanner",
  },
  {
    id: "12",
    title: "Crop PDF",
    icon: "copyright-circle",
    color: "rgba(152, 0, 0, 0.8)",
    route: "CropPdf",
  },
];

export const allToolsData = [
  {
    id: "1",
    title: "Compress PDF",
    icon: "compress",
    color: "rgba(236, 72, 153, 1)",
    route: "CompressPDF",
  },
  {
    id: "2",
    title: "Marge PDF",
    icon: "fork",
    color: "rgba(59, 130, 246, 1)",
    route: "MargePDF",
  },
  {
    id: "3",
    title: "QR Code Generator",
    icon: "qrcode",
    color: "rgba(34, 197, 94, 1)",
    route: "QrGenerator",
  },
  {
    id: "4",
    title: "Image to PDF",
    icon: "file-image",
    color: "rgba(249, 115, 22, 1)",
    route: "UploadPDF",
  },
  {
    id: "5",
    title: "Page Number",
    icon: "field-number",
    color: "rgba(139, 92, 246, 1)",
    route: "PageNumber",
  },

  {
    id: "6",
    title: "Add Header & Footer",
    icon: "file-text",
    color: "rgba(5, 132, 137, 0.8)",
    route: "AddHeaderFooter",
  },
  {
    id: "7",
    title: "Pdf Watermark",
    icon: "highlight",
    color: "rgba(245, 158, 11, 1)",
    route: "PdfWatermark",
  },
   {
    id: "8",
    title: "File",
    icon: "folder-open",
    color: "rgba(59, 130, 246, 1)",
    route: "FileManager",
  },

  {
    id: "9",
    title: "View PDF",
    icon: "file-pdf",
    color: "rgba(59, 130, 246, 1)",
    route: "FileManager",
  },
  {
    id: "10",
    title: "QR Code Scanner",
    icon: "scan",
    color: "rgba(14, 165, 233, 1)",
    route: "QrScanner",
  },
  {
    id: "11",
    title: "Crop PDF",
    icon: "copyright-circle",
    color: "rgba(152, 0, 0, 0.8)",
    route: "CropPdf",
  },
  {
    id: "12",
    title: "Resize PDF",
    icon: "block",
    color: "rgba(245, 40, 145, 0.8)",
    route: "ResizePDF",
  },
  {
    id: "13",
    title: "File to ZIP",
    icon: "file-zip",
    color: "rrgba(37, 99, 235, 1)",
    route: "UploadPDF",
  },
];
